### PR TITLE
feat: Add $SUITE_test_exclude_filter (`var testExcludeFilter`)

### PR DESCRIPTION
**Pull request by kajiya3141**
Add the ability to skip certain tests using `regexp`

* Instructions added to README.md in both the root dir and `test_suites/`

### CODE REVIEW

**Comment by kajiya3141** [comment]
Hey everyone!

Thanks for looking at my PR :smile: And apologies in advance if this code is inefficient (`go` isn't my strongest language).
I've tried to make this explicit where possible and keep to a pattern (i.e. keeping to the `TestSetup` functions) - if this looks good and is accepted I'll probably make a second pass and add filters to the remaining suites.

##### Testing
I've run this a couple of times on an ubuntu instance in GCE and it all looks good; [the output of one of the runs can be seen here](https://pastebin.ubuntu.com/p/bbdG3qMCR2/). `'-disk_test_exclude_filter=TestDiskResize|TestBlockDeviceNaming' -guestagent_test_exclude_filter=TestTelemetryEnabled -hostnamevalidation_test_exclude_filter=TestHostKeysGeneratedOnce -hotattach_test_exclude_filter=TestFileHotAttach '-imageboot_test_exclude_filter=TestGuestBoot|TestGuestReboot' -licensevalidation_test_exclude_filter=TestLicenses -livemigrate_test_exclude_filter=TestLiveMigrate -lssd_test_exclude_filter=TestMount '-mdsmtls_test_exclude_filter=TestMTLSJobScheduled|TestMTLSCredsExists' -network_test_exclude_filter=TestWaitForPing -packagevalidation_test_exclude_filter=TestGuestPackages -ssh_test_exclude_filter=TestEmptyTest -suspendresume_test_exclude_filter=TestSuspend'` was used to test a cross section of the filters.

**Comment by a-crate** [comment]
Hi Chlo - I like this idea but one of the concerns I have here is that this requires a lot of manual work from test authors and maintainers to keep each of their filter flags up to date.

I'd prefer to see a solution that allows a generic filter flag independent of the test_suite code - something like a regex union with a user supplied regex in the `--test.filter` argument in the wrapper code.

**Comment by kajiya3141** [comment]
Thanks for the comment/review Amy! You're right it is very heavy handed as-is (the huge command I put in to test a x-section of the filters was bad enough :eyes:), let me work on it a bit more to make it more generic

**Pull request closed without merging**
